In [5]:
import openpyxl
import pandas
from google.colab import drive
drive.mount('/content/drive',force_remount=True)
!ls "/content/drive/My Drive"

wb = openpyxl.load_workbook('/content/drive/MyDrive/us_youtube_trending.xlsx') #load_workbook - access an Excel file in python
sheet1 = wb['Sheet1']
data = sheet1.values
columns = next(data)[0:]
data_frame = pandas.DataFrame(data, columns = columns)

Mounted at /content/drive
'2022.05.24 Danh sách CTV GT cụm Bill Gates - Hoàng Mai.xlsx'
'Bai 1_Khai thac CSDL.xlsx'
'Colab Notebooks'
 InforeTech_EntryTest
'IOT - 132667 - 20212'
'Ngoc Lan Vu - CV Data Analyst Intern (1).pdf'
'Ngoc Lan Vu - CV Data Analyst Intern (2).pdf'
'Ngoc Lan Vu - CV Data Analyst Intern (3).pdf'
'Ngoc Lan Vu - CV Data Analyst Intern.pdf'
'Project III - Vũ Thị Ngọc Lan - 20183939'
'Secret Confession.gform'
'Slide Capstone Project - TKXDPM - 20211-converted.pptx'
'Slide Capstone Project - TKXDPM - 20211.zip'
 supermarket_sales.csv
 us_youtube_trending.xlsx

In [6]:
#delete NaN records in video_id column
data_frame.dropna(axis = 0, subset = ['video_id'])
#axis = 0: delete the rows contain the null value
#axis = 1: delete the columns contain null value

,video_id,trending_date,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled
0,2kyS6SvSYSE,2017-11-14,CaseyNeistat,22.0,2017-11-13T17:13:01.000Z,748374.0,57527.0,2966.0,15954.0,False,False
1,1ZAPwfrtAFY,2017-11-14,LastWeekTonight,24.0,2017-11-13T07:30:00.000Z,2418783.0,97185.0,6146.0,12703.0,False,False
2,5qpjK5DgCt4,2017-11-14,Rudy Mancuso,23.0,2017-11-12T19:05:24.000Z,3191434.0,146033.0,5339.0,8181.0,False,False
3,puqaWrEC7tY,2017-11-14,Good Mythical Morning,24.0,2017-11-13T11:00:04.000Z,343168.0,10172.0,666.0,2146.0,False,False
4,d380meD0W0M,2017-11-14,nigahiga,24.0,2017-11-12T18:01:41.000Z,2095731.0,132235.0,1989.0,17518.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...
9876,OVnxBcS5qWo,2018-02-01,Nintendo,20.0,2018-01-25T21:25:58.000Z,434156.0,14685.0,411.0,2277.0,False,False
9877,ltzy5vRmN8Q,2018-02-01,BURGER KING,24.0,2018-01-24T14:08:29.000Z,4003530.0,119341.0,9363.0,20414.0,False,False
9878,NEmFS50lsTw,2018-02-01,SKITTLESbrand,24.0,2018-01-24T15:31:57.000Z,483127.0,3924.0,362.0,506.0,False,False
9879,NZ0ImXT1FZk,2018-02-01,Brave Wilderness,15.0,2018-01-24T12:00:02.000Z,1417253.0,44358.0,893.0,6858.0,False,False
9880,t3z_pdr6z8w,2018-02-01,Jackie Aina,26.0,2018-01-25T05:05:42.000Z,877585.0,115391.0,1621.0,15749.0,False,False

In [7]:
#show all the duplicate records in video_id column
print(data_frame[data_frame.duplicated(subset = ['video_id'], keep = False)])
#keep = False: all the duplicate records
#keep = First: all the duplicate records except the first record(unique)
#keep = Last: all the duplicate records except the last record(unique)

         video_id trending_date          channel_title  category_id  \
0     2kyS6SvSYSE    2017-11-14           CaseyNeistat         22.0
1     1ZAPwfrtAFY    2017-11-14        LastWeekTonight         24.0
2     5qpjK5DgCt4    2017-11-14           Rudy Mancuso         23.0
3     puqaWrEC7tY    2017-11-14  Good Mythical Morning         24.0
4     d380meD0W0M    2017-11-14               nigahiga         24.0
...           ...           ...                    ...          ...
9683  OziQ_a3Rpqw    2018-01-01          HollywoodLife         24.0
9684  ydPYNo8o-lI    2018-01-01     ImagineDragonsVEVO         10.0
9685  SFxZb-GHbrQ    2018-01-01              Star Wars         24.0
9786       #NAME?    2018-02-01         Midnight Video          1.0
9792       #NAME?    2018-02-01          Extra Credits         27.0

                  publish_time      views     likes  dislikes  comment_count  \
0     2017-11-13T17:13:01.000Z   748374.0   57527.0    2966.0        15954.0
1     2017-11-13T07:30:00.000Z  2418783.0   97185.0    6146.0        12703.0
2     2017-11-12T19:05:24.000Z  3191434.0  146033.0    5339.0         8181.0
3     2017-11-13T11:00:04.000Z   343168.0   10172.0     666.0         2146.0
4     2017-11-12T18:01:41.000Z  2095731.0  132235.0    1989.0        17518.0
...                        ...        ...       ...       ...            ...
9683  2017-12-21T00:33:36.000Z   756379.0    5599.0     650.0          779.0
9684  2017-12-20T05:00:02.000Z  3266179.0  108422.0    2843.0         4768.0
9685  2017-12-20T18:00:06.000Z   398127.0    9204.0    5176.0         2758.0
9786  2018-01-29T13:00:00.000Z    60262.0    4804.0     122.0          736.0
9792  2018-01-27T18:30:12.000Z   387815.0   17593.0     248.0         1812.0

      comments_disabled  ratings_disabled
0                 False             False
1                 False             False
2                 False             False
3                 False             False
4                 False             False
...                 ...               ...
9683              False             False
9684              False             False
9685              False             False
9786              False             False
9792              False             False

[9384 rows x 11 columns]

In [8]:
#delete the duplicate records in video_id except the lastest trending date
data_frame_sorted = data_frame.sort_values('trending_date')
data_frame_sorted.drop_duplicates(subset = ['video_id'], keep = 'last')

,video_id,trending_date,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled
135,5x1FAiIq_pQ,2017-11-14,Alicia Keys,10.0,2017-11-09T15:49:21.000Z,95944.0,1354.0,181.0,117.0,False,False
138,vd4zwINEcLY,2017-11-14,poofables,24.0,2011-03-27T04:31:25.000Z,95085.0,909.0,52.0,193.0,False,False
139,7fm7mll2qvg,2017-11-14,SigridVEVO,10.0,2017-11-10T00:00:00.000Z,91776.0,4604.0,46.0,357.0,False,False
142,q-WipZ9p0wk,2017-11-14,Brothers Green Eats,26.0,2017-11-09T14:00:08.000Z,77630.0,1991.0,83.0,208.0,False,False
143,zy0b9e40tK8,2017-11-14,Netflix,24.0,2017-11-09T09:00:07.000Z,378750.0,5642.0,146.0,675.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...
9753,9NkHIv25IH4,2018-02-01,Life Noggin,27.0,2018-01-29T14:00:01.000Z,441007.0,16475.0,275.0,2840.0,False,False
9754,SJXXGL_8VcU,2018-02-01,Keith Urban,24.0,2018-01-29T21:31:34.000Z,64143.0,1782.0,111.0,122.0,False,False
9755,Dc-EG4ABsxA,2018-02-01,Austin Evans,28.0,2018-01-30T16:27:38.000Z,493457.0,17321.0,507.0,2583.0,False,False
9757,V8-JfSXPDp0,2018-02-01,The Action Lab,24.0,2018-01-28T17:23:05.000Z,1274946.0,18880.0,2749.0,3607.0,False,False
9880,t3z_pdr6z8w,2018-02-01,Jackie Aina,26.0,2018-01-25T05:05:42.000Z,877585.0,115391.0,1621.0,15749.0,False,False

In [9]:
#check the data types of column in data_frame, change trending_date and publish_time into datetime type
data_frame['trending_date'] = pandas.to_datetime(data_frame['trending_date'])
data_frame['publish_time'] = pandas.to_datetime(data_frame['publish_time'])
print(data_frame.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9881 entries, 0 to 9880
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   video_id           9881 non-null   object
 1   trending_date      9881 non-null   datetime64[ns]
 2   channel_title      9881 non-null   object
 3   category_id        9881 non-null   float64
 4   publish_time       9881 non-null   datetime64[ns, UTC]
 5   views              9881 non-null   float64
 6   likes              9881 non-null   float64
 7   dislikes           9881 non-null   float64
 8   comment_count      9881 non-null   float64
 9   comments_disabled  9881 non-null   bool
 10  ratings_disabled   9881 non-null   bool
dtypes: bool(2), datetime64[ns, UTC](1), datetime64[ns](1), float64(5), object(2)
memory usage: 714.2+ KB
None

In [10]:
#descriptive statistic
print(data_frame.describe)
print(data_frame.corr())

<bound method NDFrame.describe of          video_id trending_date          channel_title  category_id  \
0     2kyS6SvSYSE    2017-11-14           CaseyNeistat         22.0
1     1ZAPwfrtAFY    2017-11-14        LastWeekTonight         24.0
2     5qpjK5DgCt4    2017-11-14           Rudy Mancuso         23.0
3     puqaWrEC7tY    2017-11-14  Good Mythical Morning         24.0
4     d380meD0W0M    2017-11-14               nigahiga         24.0
...           ...           ...                    ...          ...
9876  OVnxBcS5qWo    2018-02-01               Nintendo         20.0
9877  ltzy5vRmN8Q    2018-02-01            BURGER KING         24.0
9878  NEmFS50lsTw    2018-02-01          SKITTLESbrand         24.0
9879  NZ0ImXT1FZk    2018-02-01       Brave Wilderness         15.0
9880  t3z_pdr6z8w    2018-02-01            Jackie Aina         26.0

                  publish_time      views     likes  dislikes  comment_count  \
0    2017-11-13 17:13:01+00:00   748374.0   57527.0    2966.0        15954.0
1    2017-11-13 07:30:00+00:00  2418783.0   97185.0    6146.0        12703.0
2    2017-11-12 19:05:24+00:00  3191434.0  146033.0    5339.0         8181.0
3    2017-11-13 11:00:04+00:00   343168.0   10172.0     666.0         2146.0
4    2017-11-12 18:01:41+00:00  2095731.0  132235.0    1989.0        17518.0
...                        ...        ...       ...       ...            ...
9876 2018-01-25 21:25:58+00:00   434156.0   14685.0     411.0         2277.0
9877 2018-01-24 14:08:29+00:00  4003530.0  119341.0    9363.0        20414.0
9878 2018-01-24 15:31:57+00:00   483127.0    3924.0     362.0          506.0
9879 2018-01-24 12:00:02+00:00  1417253.0   44358.0     893.0         6858.0
9880 2018-01-25 05:05:42+00:00   877585.0  115391.0    1621.0        15749.0

      comments_disabled  ratings_disabled
0                 False             False
1                 False             False
2                 False             False
3                 False             False
4                 False             False
...                 ...               ...
9876              False             False
9877              False             False
9878              False             False
9879              False             False
9880              False             False

[9881 rows x 11 columns]>
                   category_id     views     likes  dislikes  comment_count  \
category_id           1.000000 -0.068531 -0.092913  0.002402      -0.022163
views                -0.068531  1.000000  0.880433  0.673456       0.775262
likes                -0.092913  0.880433  1.000000  0.530022       0.850243
dislikes              0.002402  0.673456  0.530022  1.000000       0.756843
comment_count        -0.022163  0.775262  0.850243  0.756843       1.000000
comments_disabled     0.053657 -0.017610 -0.030216 -0.000411      -0.026670
ratings_disabled     -0.052243 -0.010271 -0.019651 -0.005567      -0.012661

                   comments_disabled  ratings_disabled
category_id                 0.053657         -0.052243
views                      -0.017610         -0.010271
likes                      -0.030216         -0.019651
dislikes                   -0.000411         -0.005567
comment_count              -0.026670         -0.012661
comments_disabled           1.000000          0.324941
ratings_disabled            0.324941          1.000000

In [11]:
#sort data by channel_title column (A-Z) and views column (DESC)
data_frame.sort_values(by = ['channel_title', 'views'], ascending = [True, False])

,video_id,trending_date,channel_title,category_id,publish_time,views,likes,dislikes,comment_count,comments_disabled,ratings_disabled
550,9KIP-Ncp2jU,2017-11-16,12 News,22.0,2017-11-11 01:03:01+00:00,92327.0,182.0,45.0,0.0,False,False
315,9KIP-Ncp2jU,2017-11-15,12 News,22.0,2017-11-11 01:03:01+00:00,85643.0,170.0,45.0,0.0,False,False
1968,8-Cjsnq8kVU,2017-11-23,20th Century Fox,1.0,2017-11-15 14:01:03+00:00,12382809.0,328876.0,7238.0,14836.0,False,False
1728,8-Cjsnq8kVU,2017-11-22,20th Century Fox,1.0,2017-11-15 14:01:03+00:00,11907002.0,320679.0,7145.0,14357.0,False,False
1498,8-Cjsnq8kVU,2017-11-21,20th Century Fox,1.0,2017-11-15 14:01:03+00:00,11362593.0,311331.0,6888.0,13985.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...
7821,NePlddZpNKs,2017-12-23,wdwmagic,19.0,2017-12-18 22:00:48+00:00,1028272.0,11643.0,8835.0,9649.0,False,False
7592,NePlddZpNKs,2017-12-22,wdwmagic,19.0,2017-12-18 22:00:48+00:00,1010286.0,11578.0,8786.0,9515.0,False,False
7350,NePlddZpNKs,2017-12-21,wdwmagic,19.0,2017-12-18 22:00:48+00:00,966532.0,11380.0,8648.0,9775.0,False,False
7130,NePlddZpNKs,2017-12-20,wdwmagic,19.0,2017-12-18 22:00:48+00:00,792374.0,10060.0,7688.0,8804.0,False,False
6921,NePlddZpNKs,2017-12-19,wdwmagic,19.0,2017-12-18 22:00:48+00:00,188213.0,4174.0,2743.0,2525.0,False,False

In [12]:
#filter videos which views > 10000000 and likes > 100000 and select 5 highest comment_count
!pip install pandasql
import pandasql
from pandasql import sqldf
q1 = "SELECT * FROM data_frame WHERE views > 10000000 AND likes > 100000 ORDER BY comment_count DESC LIMIT (5);"
print(sqldf(q1))

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandasql in /usr/local/lib/python3.7/dist-packages (0.7.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.4.36)
Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.3.5)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from pandasql) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas->pandasql) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas->pandasql) (1.15.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (1.1.2)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.7/dist-packages (from sqlalchemy->pandasql) (4.11.4)
Requirement already satisfied: typing-extensions>=3.6.4 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (4.2.0)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.7/dist-packages (from importlib-metadata->sqlalchemy->pandasql) (3.8.0)
      video_id               trending_date      channel_title  category_id  \
0  FlsCjmMhFmw  2017-12-09 00:00:00.000000  YouTube Spotlight         24.0
1  FlsCjmMhFmw  2017-12-13 00:00:00.000000  YouTube Spotlight         24.0
2  FlsCjmMhFmw  2017-12-14 00:00:00.000000  YouTube Spotlight         24.0
3  FlsCjmMhFmw  2017-12-12 00:00:00.000000  YouTube Spotlight         24.0
4  FlsCjmMhFmw  2017-12-11 00:00:00.000000  YouTube Spotlight         24.0

                 publish_time        views      likes   dislikes  \
0  2017-12-06 17:58:51.000000   75969469.0  2251797.0  1127798.0
1  2017-12-06 17:58:51.000000  137843120.0  3014471.0  1602383.0
2  2017-12-06 17:58:51.000000  149376127.0  3093544.0  1643059.0
3  2017-12-06 17:58:51.000000  125432237.0  2912702.0  1545015.0
4  2017-12-06 17:58:51.000000  113874632.0  2811215.0  1470383.0

   comment_count  comments_disabled  ratings_disabled
0       827755.0                  0                 0
1       817582.0                  0                 0
2       810698.0                  0                 0
3       807558.0                  0                 0
4       787174.0                  0                 0

In [17]:
#filter video which comment and rating are disable, count the records each category
q2 = "SELECT * FROM data_frame WHERE comments_disabled = 1;"
print(sqldf(q2))
q3 = "SELECT * FROM data_frame WHERE ratings_disabled = 1;"
print(sqldf(q3))
q4 = "SELECT COUNT(*) FROM data_frame WHERE comments_disabled = 1;"
print(sqldf(q4))
q5 = "SELECT COUNT(*) FROM data_frame WHERE ratings_disabled = 1;"
print(sqldf(q5))

        video_id               trending_date        channel_title  \
0    CBVGjS_EJok  2017-11-14 00:00:00.000000         Amazon.co.uk
1    9oFP-pOMNwE  2017-11-14 00:00:00.000000                  H&M
2    CBVGjS_EJok  2017-11-15 00:00:00.000000         Amazon.co.uk
3    9oFP-pOMNwE  2017-11-15 00:00:00.000000                  H&M
4    Hq89wYzOjfs  2017-11-16 00:00:00.000000               Summit
..           ...                         ...                  ...
186  tE5C3O71Xqo  2018-01-01 00:00:00.000000         Doug Ellison
187  kUZlz6VbMCg  2018-02-01 00:00:00.000000         PBS NewsHour
188  6oIWl1jLE20  2018-02-01 00:00:00.000000                Slooh
189  4Ek6UCI0YQs  2018-02-01 00:00:00.000000          Kevin Stein
190  JWAvRIpuj1U  2018-02-01 00:00:00.000000  Alpha Entertainment

     category_id                publish_time      views    likes  dislikes  \
0           24.0  2017-11-06 17:52:50.000000    26000.0    119.0      69.0
1           24.0  2017-11-09 08:01:40.000000   264793.0   3283.0     853.0
2           24.0  2017-11-06 17:52:50.000000    94229.0    217.0     177.0
3           24.0  2017-11-09 08:01:40.000000   271685.0   3330.0     854.0
4           27.0  2017-11-14 17:37:20.000000    11769.0    127.0      13.0
..           ...                         ...        ...      ...       ...
186         28.0  2017-12-23 02:02:34.000000  2193840.0  25089.0    1780.0
187         25.0  2018-01-31 17:44:20.000000  4857665.0  32918.0    2603.0
188         28.0  2018-01-31 16:25:47.000000   269906.0      0.0       0.0
189         27.0  2015-09-21 21:46:40.000000     2452.0      2.0       0.0
190         17.0  2018-01-25 20:30:17.000000   139068.0      0.0       0.0

     comment_count  comments_disabled  ratings_disabled
0              0.0                  1                 0
1              0.0                  1                 0
2              0.0                  1                 0
3              0.0                  1                 0
4              0.0                  1                 0
..             ...                ...               ...
186            0.0                  1                 0
187            0.0                  1                 0
188            0.0                  1                 1
189            0.0                  1                 0
190            0.0                  1                 1

[191 rows x 11 columns]
       video_id               trending_date                 channel_title  \
0   Kn5UgGQukYQ  2017-11-21 00:00:00.000000            hudsonunionsociety
1   Kn5UgGQukYQ  2017-11-22 00:00:00.000000            hudsonunionsociety
2   _akwfRuL4os  2017-11-23 00:00:00.000000                     chris lee
3   Kn5UgGQukYQ  2017-11-23 00:00:00.000000            hudsonunionsociety
4   _akwfRuL4os  2017-11-24 00:00:00.000000                     Chris Lee
5   Kn5UgGQukYQ  2017-11-24 00:00:00.000000            hudsonunionsociety
6   _akwfRuL4os  2017-11-25 00:00:00.000000                     Chris Lee
7   Kn5UgGQukYQ  2017-11-25 00:00:00.000000            hudsonunionsociety
8   tj3EKWwIulQ  2017-11-26 00:00:00.000000                         HARRY
9   _akwfRuL4os  2017-11-26 00:00:00.000000                     Chris Lee
10  Kn5UgGQukYQ  2017-11-26 00:00:00.000000            hudsonunionsociety
11  tj3EKWwIulQ  2017-11-27 00:00:00.000000                         HARRY
12  _akwfRuL4os  2017-11-27 00:00:00.000000                     Chris Lee
13  Kn5UgGQukYQ  2017-11-27 00:00:00.000000            hudsonunionsociety
14  tj3EKWwIulQ  2017-11-28 00:00:00.000000                         HARRY
15  tj3EKWwIulQ  2017-11-29 00:00:00.000000                         HARRY
16  nx1R-eHSkfM  2017-11-30 00:00:00.000000                      Snapchat
17  aLSG3178eD4  2017-11-30 00:00:00.000000               Define American
18  nx1R-eHSkfM  2017-12-01 00:00:00.000000                      Snapchat
19  aLSG3178eD4  2017-12-01 00:00:00.000000               Define American
20  nx1R-eHSkfM  2017-12-02 00:00:00.000000                      Snapchat
21  aLSG3178eD4  2017-12-02 00:00:00.000000               Define American
22  nx1R-eHSkfM  2017-12-03 00:00:00.000000                      Snapchat
23  aLSG3178eD4  2017-12-03 00:00:00.000000               Define American
24  nx1R-eHSkfM  2017-12-04 00:00:00.000000                      Snapchat
25  l5S5DM564O8  2017-12-05 00:00:00.000000               Pac-12 Networks
26  nx1R-eHSkfM  2017-12-05 00:00:00.000000                      Snapchat
27  l5S5DM564O8  2017-12-06 00:00:00.000000               Pac-12 Networks
28  nx1R-eHSkfM  2017-12-06 00:00:00.000000                      Snapchat
29  l5S5DM564O8  2017-12-07 00:00:00.000000               Pac-12 Networks
30  nx1R-eHSkfM  2017-12-07 00:00:00.000000                      Snapchat
31  l5S5DM564O8  2017-12-08 00:00:00.000000               Pac-12 Networks
32  l5S5DM564O8  2017-12-09 00:00:00.000000               Pac-12 Networks
33  l5S5DM564O8  2017-12-10 00:00:00.000000               Pac-12 Networks
34  PRHVfIbeGpQ  2017-12-14 00:00:00.000000  American Bridge 21st Century
35  csqXekWeBYo  2017-12-20 00:00:00.000000              Sports Lovers n1
36  csqXekWeBYo  2017-12-21 00:00:00.000000              Sports Lovers n1
37  csqXekWeBYo  2017-12-22 00:00:00.000000              Sports Lovers n1
38  csqXekWeBYo  2017-12-23 00:00:00.000000              Sports Lovers n1
39  WIWb8f1WIyQ  2017-12-26 00:00:00.000000      Famous Celebrities Snaps
40  WIWb8f1WIyQ  2017-12-27 00:00:00.000000      Famous Celebrities Snaps
41  WIWb8f1WIyQ  2017-12-28 00:00:00.000000      Famous Celebrities Snaps
42  WIWb8f1WIyQ  2017-12-29 00:00:00.000000      Famous Celebrities Snaps
43  WIWb8f1WIyQ  2017-12-30 00:00:00.000000      Famous Celebrities Snaps
44  WIWb8f1WIyQ  2017-12-31 00:00:00.000000      Famous Celebrities Snaps
45  WIWb8f1WIyQ  2018-01-01 00:00:00.000000      Famous Celebrities Snaps
46  6oIWl1jLE20  2018-02-01 00:00:00.000000                         Slooh
47  8qW6fjiMhgo  2018-02-01 00:00:00.000000               Caravan Carolyn
48  JWAvRIpuj1U  2018-02-01 00:00:00.000000           Alpha Entertainment

    category_id                publish_time      views  likes  dislikes  \
0           1.0  2016-10-14 21:14:51.000000    15058.0    0.0       0.0
1           1.0  2016-10-14 21:14:51.000000    34207.0    0.0       0.0
2          22.0  2017-11-21 19:29:03.000000   160012.0    0.0       0.0
3           1.0  2016-10-14 21:14:51.000000    36137.0    0.0       0.0
4          22.0  2017-11-21 19:29:03.000000   179448.0    0.0       0.0
5           1.0  2016-10-14 21:14:51.000000    36579.0    0.0       0.0
6          22.0  2017-11-21 19:29:03.000000   187973.0    0.0       0.0
7           1.0  2016-10-14 21:14:51.000000    36931.0    0.0       0.0
8          24.0  2017-11-22 19:00:16.000000     3560.0    0.0       0.0
9          22.0  2017-11-21 19:29:03.000000   193362.0    0.0       0.0
10          1.0  2016-10-14 21:14:51.000000    37183.0    0.0       0.0
11         24.0  2017-11-22 19:00:16.000000     3780.0    0.0       0.0
12         22.0  2017-11-21 19:29:03.000000   196933.0    0.0       0.0
13          1.0  2016-10-14 21:14:51.000000    37346.0    0.0       0.0
14         24.0  2017-11-22 19:00:16.000000     3921.0    0.0       0.0
15         24.0  2017-11-22 19:00:16.000000     4050.0    0.0       0.0
16         10.0  2017-11-29 14:00:03.000000   867588.0    0.0       0.0
17         29.0  2017-11-28 13:00:35.000000     1456.0    0.0       0.0
18         10.0  2017-11-29 14:00:03.000000  1894443.0    0.0       0.0
19         29.0  2017-11-28 13:00:35.000000     1873.0    0.0       0.0
20         10.0  2017-11-29 14:00:03.000000  2564402.0    0.0       0.0
21         29.0  2017-11-28 13:00:35.000000     2005.0    0.0       0.0
22         10.0  2017-11-29 14:00:03.000000  2944563.0    0.0       0.0
23         29.0  2017-11-28 13:00:35.000000     2093.0    0.0       0.0
24         10.0  2017-11-29 14:00:03.000000  3206396.0    0.0       0.0
25         17.0  2017-12-04 18:32:36.000000    19333.0    0.0       0.0
26         10.0  2017-11-29 14:00:03.000000  3352913.0    0.0       0.0
27         17.0  2017-12-04 18:32:36.000000    29988.0    0.0       0.0
28         10.0  2017-11-29 14:00:03.000000  3449247.0    0.0       0.0
29         17.0  2017-12-04 18:32:36.000000    33012.0    0.0       0.0
30         10.0  2017-11-29 14:00:03.000000  3511909.0    0.0       0.0
31         17.0  2017-12-04 18:32:36.000000    34794.0    0.0       0.0
32         17.0  2017-12-04 18:32:36.000000    35830.0    0.0       0.0
33         17.0  2017-12-04 18:32:36.000000    36929.0    0.0       0.0
34         25.0  2017-12-11 14:54:32.000000    22690.0    0.0       0.0
35         22.0  2017-12-18 19:02:21.000000    31323.0    0.0       0.0
36         22.0  2017-12-18 19:02:21.000000    34123.0    0.0       0.0
37         22.0  2017-12-18 19:02:21.000000    35410.0    0.0       0.0
38         22.0  2017-12-18 19:02:21.000000    35916.0    0.0       0.0
39          2.0  2017-12-25 03:08:33.000000   231947.0    0.0       0.0
40          2.0  2017-12-25 03:08:33.000000   402276.0    0.0       0.0
41          2.0  2017-12-25 03:08:33.000000   455772.0    0.0       0.0
42          2.0  2017-12-25 03:08:33.000000   466398.0    0.0       0.0
43          2.0  2017-12-25 03:08:33.000000   471027.0    0.0       0.0
44          2.0  2017-12-25 03:08:33.000000   474458.0    0.0       0.0
45          2.0  2017-12-25 03:08:33.000000   477976.0    0.0       0.0
46         28.0  2018-01-31 16:25:47.000000   269906.0    0.0       0.0
47         22.0  2018-01-27 22:12:08.000000    24540.0    0.0       0.0
48         17.0  2018-01-25 20:30:17.000000   139068.0    0.0       0.0

    comment_count  comments_disabled  ratings_disabled
0             0.0                  1                 1
1             0.0                  1                 1
2          1722.0                  0                 1
3             0.0                  1                 1
4          1847.0                  0                 1
5             0.0                  1                 1
6          1919.0                  0                 1
7             0.0                  1                 1
8             0.0                  1                 1
9          1958.0                  0                 1
10            0.0                  1                 1
11            0.0                  1                 1
12         1947.0                  0                 1
13            0.0                  1                 1
14            0.0                  1                 1
15            0.0                  1                 1
16            0.0                  1                 1
17            0.0                  1                 1
18            0.0                  1                 1
19            0.0                  1                 1
20            0.0                  1                 1
21            0.0                  1                 1
22            0.0                  1                 1
23            0.0                  1                 1
24            0.0                  1                 1
25            0.0                  1                 1
26            0.0                  1                 1
27            0.0                  1                 1
28            0.0                  1                 1
29            0.0                  1                 1
30            0.0                  1                 1
31            0.0                  1                 1
32            0.0                  1                 1
33            0.0                  1                 1
34            0.0                  1                 1
35           42.0                  0                 1
36           54.0                  0                 1
37           64.0                  0                 1
38           70.0                  0                 1
39          697.0                  0                 1
40          960.0                  0                 1
41          756.0                  0                 1
42          780.0                  0                 1
43          787.0                  0                 1
44          789.0                  0                 1
45          777.0                  0                 1
46            0.0                  1                 1
47          770.0                  0                 1
48            0.0                  1                 1
   COUNT(*)
0       191
   COUNT(*)
0        49